

CREATE DATABASE Lavarapido;

USE Lavarapido;

CREATE TABLE TB_Empresa(

Id INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Endereco VARCHAR(30) NOT NULL,
Telefone VARCHAR(15) NOT NULL
);

CREATE TABLE TB_Funcionario(

Id INT AUTO_INCREMENT PRIMARY KEY,
IdEmpresa INT  NOT NULL,,
Nome VARCHAR(50) NOT NULL,
Cargo VARCHAR(30) NOT NULL,
FOREIGN KEY (IdEmpresa) REFERENCES TB_Empresa(Id)
);

CREATE TABLE TB_Cliente(

Id INT AUTO_INCREMENT PRIMARY KEY,
IdEmpresa INT NOT NULL,
Nome VARCHAR(50) NOT NULL,
Cpf VARCHAR(14) NOT NULL,
Telefone VARCHAR(15) NOT NULL,
FOREIGN KEY(IdEmpresa) REFERENCES TB_Empresa(Id)

);

CREATE TABLE TB_Veiculo(

Id INT AUTO_INCREMENT PRIMARY KEY,
IdCliente INT NOT NULL,
Marca VARCHAR(15)NOT NULL,
Modelo VARCHAR(15)NOT NULL,
Placa VARCHAR (7)NOT NULL,
FOREIGN KEY(IdCliente) REFERENCES TB_Cliente(Id)

);

CREATE TABLE TB_Lavagem(

Id INT AUTO_INCREMENT PRIMARY KEY,
IdFuncionario INT NOT NULL,
Valor DECIMAL(10,2),
DataLavagem DATE,
FOREIGN KEY(IdFuncionario) REFERENCES TB_Funcionario(Id)

);

CREATE TABLE TB_Veiculo_Lavagem(
IdVeiculo INT NOT NULL,
IdLavagem INT NOT NULL,
FOREIGN KEY(IdVeiculo) REFERENCES TB_Veiculo(Id),
FOREIGN KEY(IdLavagem) REFERENCES TB_Lavagem(Id)

);
